apiVersion: v1
kind: Pod
metadata:
  name: vulkan-demo
  namespace: default
spec:
  containers:
  - name: vulkan-demo
    image: local/d1
    imagePullPolicy: Never
    command: ["sh", "-c" , "trap 'exit 0' TERM; while true; do sleep 60 & wait; done"]
    resources:
      limits:
        squat.ai/dri: 1
