apiVersion: v1
kind: Pod
metadata:
  name: vulkan-demo
  namespace: default
spec:
  containers:
  - name: vulkan-demo
    image: local/d1
    imagePullPolicy: Never
    command: ["/vulkan_minimal_compute"]
    env:
    - name: VK_INSTANCE_LAYERS
      value: ""
    resources:
      limits:
        squat.ai/dri: 1
    volumeMounts:
    - mountPath: /dev
      name: dev
    securityContext:
      privileged: true
  volumes:
  - name: dev
    hostPath:
      path: /dev
