apiVersion: v1
kind: Pod
metadata:
  name: vulkan-demo
  namespace: default
spec:
  containers:
  - name: vulkan-demo
    image: local/d1
    imagePullPolicy: Never
    command: ["/vulkan_minimal_compute"]
    resources:
      limits:
        squat.ai/dri: 1
