apiVersion: v1
kind: Pod
metadata:
  name: uvkc-gpu
  namespace: default
spec:
  containers:
  - name: uvkc
    image: quay.io/nirsof/uvkc:v1
    command: ["sh", "-c" , "trap 'exit 0' TERM; while true; do sleep 60 & wait; done"]
    resources:
      limits:
        squat.ai/dri: 1
